name: "GO"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.step1.outputs.url }} # map step output to job output
    steps:
      - id: step1
        name: send url to other job
        run: echo "::set-output name=url::https://google.com"

  job2:
    runs-on: ubuntu-latest
    name: "COVERAGE-->${{ needs.job1.outputs.url }}"
    needs: job1
    steps:
      - run: echo "COVERAGE-->${{ needs.job1.outputs.url }}"

  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    outputs:
      coverage: ${{ steps.coverage.outputs.coverage}} # map step output to job output
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # with:
      #   ref: ${{ github.event.pull_request.head.sha }}
      #
      - name: "pwd"
        run: pwd

      - name: "warning"
        run: 'echo "::warning file=test,line=1,col=1,endColumn=2::INVALID THING"'

      - id: "coverage"
        run: echo "::set-output name=coverage::10"
  job3:
    runs-on: ubuntu-latest
    name: "Coverage ${{ needs.test.outputs.coverage }} "
    needs: test
    steps:
      - run: "echo COVER-->${{ needs.test.outputs.coverage }}"
