name: "GO"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    outputs:
      coverage: ${{ steps.coverage.outputs.coverage}} # map step output to job output
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # with:
      #   ref: ${{ github.event.pull_request.head.sha }}
      #
      - name: "pwd"
        run: pwd

      - name: "warning"
        run: 'echo "::warning file=test,line=1,col=1,endColumn=2::INVALID THING"'

      - name: "DATA"
        id: coverage
        run: echo "::set-output coverage=10"
  job2:
    runs-on: ubuntu-latest
    name: "Coverage ${{ needs.test.outputs.coverage }} "
    needs: test
    steps:
      - run: echo "${{ needs.test.outputs.coverage }}"
