name: "GO"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # with:
      #   ref: ${{ github.event.pull_request.head.sha }}
      #
      - name: "pwd"
        run: pwd

      - name: "warning"
        run: 'echo "::warning file=test,line=1,col=1,endColumn=2::INVALID THING"'
