name: "GO"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.step1.outputs.url }} # map step output to job output
    steps:
      - id: step1
        name: send url to other job
        run: echo "::set-output name=url::https://google.com"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: user/some-action@v1
        with:
          url: ${{ needs.job1.outputs.url }} # grab job output here
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    outputs:
      coverage: ${{ steps.coverage.outputs.coverage}} # map step output to job output
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # with:
      #   ref: ${{ github.event.pull_request.head.sha }}
      #
      - name: "pwd"
        run: pwd

      - name: "warning"
        run: 'echo "::warning file=test,line=1,col=1,endColumn=2::INVALID THING"'

      - name: "DATA"
        id: coverage
        run: echo "::set-output coverage=10"
  job2:
    runs-on: ubuntu-latest
    name: "Coverage ${{ needs.test.outputs.coverage }} "
    needs: test
    steps:
      - run: echo "${{ needs.test.outputs.coverage }}"
